title : Blog Title
tagline: Blog Tagline
author :
  name : Ramnath Vaidyanathan
  email : blah@email.test
  github : ramnathv
  twitter : ramnath_vaidya
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  - new.md